### ISSUE TITLE
TextEditor.setScrollTop is deprecated.

### ISSUE THREAD

**Issue by youssef1337** [JoshCheek/atom-seeing-is-believing#29] opened 2017-01-31 23:21 UTC
This is now a view method. Call TextEditorElement::setScrollTop instead.
```
TextEditor.setScrollTop (/usr/share/atom/resources/app.asar/src/text-editor.js:3494:12)
Object.withoutMovingScreenOrCursor (/home/joe/.atom/packages/seeing-is-believing/lib/seeing-is-believing.coffee:111:21)
<unknown> (/home/joe/.atom/packages/seeing-is-believing/lib/seeing-is-believing.coffee:66:26)
ChildProcess.<anonymous> (/home/joe/.atom/packages/seeing-is-believing/lib/seeing-is-believing.coffee:95:16)
emitTwo (events.js:106:13)
ChildProcess.emit (events.js:191:7)
```

**Comment by JoshCheek** [comment] 2017-02-03 20:55
Ty, going to look at it now. Closing the issue as a duplicate of #28

**Closed by JoshCheek** 2017-02-03 20:55 UTC

**Comment by JoshCheek** [comment] 2017-02-04 02:24
Should be fixed and released, ty for reporting!

**Comment by youssef1337** [comment] 2017-02-04 11:05
Oh, didn't see the other report, I apologize and thank for fixing the issue.
